### ISSUE TITLE
Why do you choose Resilience4j

### ISSUE THREAD

**Issue by HelloTo4x** [gagansharma2717/Banking_Microservices#30]
Hi, i am reading your project, i have a question, why do u choose Resilience4j instead of Hystrix for Circuit Breaker ? Can u tell me the pros and cons of Resilienece4j

**Comment by gagansharma2717** [comment]
Hi, Netflix Hystrix as it is in a maintenance mode as of 2018. It also comes with other transitive dependencis. However,  Resilience4J is a standalone library inspired by Hystrix but build on the principles of Functional Programming. Resilience4J will be the best option to handle fault tolerance.
